services:
  php:
    extends:
      file: ../compose.yml
      service: php

  postgres:
    extends:
      file: ../compose.yml
      service: postgres

  adminer:
    image: adminer:5.4.0
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  database:
