services:
  mariadb:
    extends:
      file: ../compose.yml
      service: mariadb

  adminer:
    image: adminer:5.4.0
    ports:
      - 8081:8080
    depends_on:
      - mariadb

volumes:
  database:
