services:
  mariadb:
    image: mariadb:12.0.2
    volumes:
      - database:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
